# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 10:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timedelta.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('schedule_end', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('profit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=11)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('offer', models.FloatField()),
                ('end_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cost_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('description', models.TextField(default=' ')),
                ('duration', timedelta.fields.TimedeltaField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appointment.Store')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appointment.Store'),
        ),
        migrations.AddField(
            model_name='offer',
            name='treatment',
            field=models.ManyToManyField(blank=True, null=True, to='appointment.Treatment'),
        ),
        migrations.AddField(
            model_name='employee',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appointment.Store'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set([('name', 'contact')]),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appointment.Employee'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appointment.Customer'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointment.Offer'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='treatment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='appointment.Treatment'),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together=set([('name', 'address')]),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set([('name', 'store', 'address', 'email')]),
        ),
    ]
