from django.conf.urls import url
from django.contrib import admin

from .views import (
    custom_check,
    custom_create,
    appointment_list,
    appointment_create,
    appointment_set,
    appointment_store,
    appointment_update_others,
    appointment_delete,
    monthly_appointment,
    create_offer,
    create_treat,
    create_employee,
    offer_list,
    offer_update,
    offer_delete,
    treat_list,
    treat_update,
    treat_delete,
    employee_list,
    employee_update,
    employee_delete,
    employee_details,
    )

urlpatterns = [
    url(r'^(?P<id>\d+)/ccheck/$', custom_check, name="customcheck"),
    url(r'^(?P<id>\d+)/coffer/$', create_offer, name="createoffer"),
    url(r'^(?P<id>\d+)/list_offer/$', offer_list, name="list_offer"),
    url(r'^(?P<id>\d+)/deloffer/(?P<aid>\d+)/$', offer_delete, name="deloffer"),
    url(r'^(?P<id>\d+)/uoffer/(?P<aid>\d+)/$', offer_update, name="uoffer"),
    url(r'^(?P<id>\d+)/ctreat/$', create_treat, name="createtreat"),
    url(r'^(?P<id>\d+)/list_treat/$', treat_list, name="list_treat"),
    url(r'^(?P<id>\d+)/deltreat/(?P<aid>\d+)/$', treat_delete, name="deltreat"),
    url(r'^(?P<id>\d+)/utreat/(?P<aid>\d+)/$', treat_update, name="utreat"),
    url(r'^(?P<id>\d+)/cemployee/$', create_employee, name="createemployee"),
    url(r'^(?P<id>\d+)/list_employee/$', employee_list, name="list_employee"),
    url(r'^(?P<id>\d+)/delemployee/(?P<aid>\d+)/$', employee_delete, name="delemployee"),
    url(r'^(?P<id>\d+)/uemployee/(?P<aid>\d+)/$', employee_update, name="uemployee"),
    url(r'^(?P<id>\d+)/ccreate/(?P<contact>\d+)/$', custom_create, name="customcreate"),
    url(r'^(?P<id>\d+)/applist/$', appointment_list, name="appointlist"),
    url(r'^(?P<id>\d+)/create/(?P<cid>\d+)/$', appointment_create, name="appointcreate"),
    url(r'^(?P<id>\d+)/set/(?P<cid>\d+)/$', appointment_set, name="appointset"),
    url(r'^(?P<id>\d+)/$', appointment_store, name="store"),
    url(r'^(?P<id>\d+)/update/(?P<cid>\d+)/$', appointment_update_others, name="appointupdate"),
    url(r'^(?P<id>\d+)/delete/(?P<cid>\d+)/$', appointment_delete, name="appointdelete"),
    url(r'^(?P<id>\d+)/monthlist/$', monthly_appointment, name="monthlist"),
    url(r'^(?P<id>\d+)/empdetails/(?P<eid>\d+)/$', employee_details, name="empdetails"),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]
